Se words spacy
sophieball/toxicity-detector pull request #79
Opened 2020-08-20 00:12 UTC by sophieball

2020-09-10 16:48 UTC, CaptainEmerson requested changes

2020-09-10 16:48 UTC, CaptainEmerson commented on src/BUILD
> +        requirement("scipy")
Still need joblib here

2020-09-10 16:48 UTC, CaptainEmerson commented on main/train_classifier_g.py
> +    #predict_unlabeled(unlabeled, trained_model, feature_set[0])
rm?

2020-09-10 16:48 UTC, CaptainEmerson commented on src/find_SE_words.py
> +  review_comments = review_comments.sample(num_kaggle)
```
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/find_SE_words.runfiles/__main__/src/find_SE_words.py", line 51, in <module>
    review_comments = review_comments.sample(num_kaggle)
AttributeError: 'list' object has no attribute 'sample'
```

2020-09-18 01:51 UTC, sophieball commented on src/BUILD
> +        requirement("scipy")
added

2020-09-18 01:51 UTC, sophieball commented on main/train_classifier_g.py
> +    #predict_unlabeled(unlabeled, trained_model, feature_set[0])
removed

2020-09-18 01:51 UTC, sophieball commented on src/find_SE_words.py
> +  review_comments = review_comments.sample(num_kaggle)
fixed

2020-09-21 22:32 UTC, CaptainEmerson commented
Seems to work for me. I get:
```
Vocab size is 14957
Comparing language...
```

But I'm not sure what this comment was for:
> Please move SE_words_GH_zscores.csv and SE_words_GH.list to src/data/

2020-09-21 22:32 UTC, CaptainEmerson approved these changes

2020-09-22 03:55 UTC, sophieball commented
> Seems to work for me. I get:
> 
> ```
> Vocab size is 14957
> Comparing language...
> ```
> 
> But I'm not sure what this comment was for:
> 
> > Please move SE_words_GH_zscores.csv and SE_words_GH.list to src/data/

`//src:find_SE_words` generates these two files (I think it should be G instead of GH). We need to save it for classifier training.

2020-09-22 03:55 UTC, merged